# will the functions be lambdas or names of already defined functions (or both)

# nodes are on the outermiost level of this document
[start]
  # the denominator, given the probability of each edge is a simple fraction
  # which will then be recalculated depending on configurations
  basis = 9

  # each subsequent submap is an edge in the fsm
  [is_tom]
  # the nominator of the probability fraction
  probability = 1
  # either a lambda function or the name of an existing function
  # all transformations are functions that accept bytes and return bytes
  transformation = "x^2"
  # name of the next state; if missing, that's a final state
  # it either has to be defined in this list or can be the name of another fsm
  next_state = "cartoon"
  [is_jerry]
  probability = 8
  transformation = "x^2"
  next_state = "cartoon"
  [is_else]
  # no probability filed needed because this is the last edge
  transformation = "x+'a'"
  # no next_state field because this is a final state

[cartoon]
  basis = 2

  [is_wb]
  probability = 1
  transformation = "x/2"

  [is_disney]
  transformation = "x - 1"
